Traceback (most recent call last):
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 235, in run
    self.play_game(challenge=challenge)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 199, in play_game
    gamestate = self.create_initial_gamestate()
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 91, in create_initial_gamestate
    moves = [x[0] for x in poke.predict_moves([])]
  File "/home/vasu/Work/pokemon_ai/showdown_ai/team.py", line 171, in predict_moves
    return self.predictor(known_moves)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/move_predict.py", line 14, in __call__
    return self.get_moves(*args)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/move_predict.py", line 42, in get_moves
    del move_freq[move]
TypeError: list indices must be integers, not tuple
