Traceback (most recent call last):
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 258, in run
    self.play_game(challenge=challenge)
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 237, in play_game
    self.selenium.switch(move.switch_index, move.backup_switch)
  File "c:\users\vikram\pokemon_ai\showdown_ai\browser.py", line 205, in switch
    self.backup_switch(backup_switch)
  File "c:\users\vikram\pokemon_ai\showdown_ai\browser.py", line 214, in backup_switch
    buttons[i].click()
IndexError: list index out of range
