Traceback (most recent call last):
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 192, in run
    self.play_game(challenge=challenge)
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 155, in play_game
    gamestate = self.create_initial_gamestate()
  File "c:\users\vikram\pokemon_ai\showdown_ai\showdown.py", line 64, in create_initial_gamestate
    assert len(moveset), "No candidate movesets for %s" % name
AssertionError: No candidate movesets for Caterpie
